/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterBusinessRouteImport } from './routes/register-business'
import { Route as RecommendRouteImport } from './routes/recommend'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DestinationsIndexRouteImport } from './routes/destinations.index'
import { Route as DestinationsIdRouteImport } from './routes/destinations.$id'

const RegisterBusinessRoute = RegisterBusinessRouteImport.update({
  id: '/register-business',
  path: '/register-business',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendRoute = RecommendRouteImport.update({
  id: '/recommend',
  path: '/recommend',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsIndexRoute = DestinationsIndexRouteImport.update({
  id: '/destinations/',
  path: '/destinations/',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsIdRoute = DestinationsIdRouteImport.update({
  id: '/destinations/$id',
  path: '/destinations/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/recommend': typeof RecommendRoute
  '/register-business': typeof RegisterBusinessRoute
  '/destinations/$id': typeof DestinationsIdRoute
  '/destinations/': typeof DestinationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/recommend': typeof RecommendRoute
  '/register-business': typeof RegisterBusinessRoute
  '/destinations/$id': typeof DestinationsIdRoute
  '/destinations': typeof DestinationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/recommend': typeof RecommendRoute
  '/register-business': typeof RegisterBusinessRoute
  '/destinations/$id': typeof DestinationsIdRoute
  '/destinations/': typeof DestinationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/history'
    | '/recommend'
    | '/register-business'
    | '/destinations/$id'
    | '/destinations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/history'
    | '/recommend'
    | '/register-business'
    | '/destinations/$id'
    | '/destinations'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/history'
    | '/recommend'
    | '/register-business'
    | '/destinations/$id'
    | '/destinations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  HistoryRoute: typeof HistoryRoute
  RecommendRoute: typeof RecommendRoute
  RegisterBusinessRoute: typeof RegisterBusinessRoute
  DestinationsIdRoute: typeof DestinationsIdRoute
  DestinationsIndexRoute: typeof DestinationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register-business': {
      id: '/register-business'
      path: '/register-business'
      fullPath: '/register-business'
      preLoaderRoute: typeof RegisterBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommend': {
      id: '/recommend'
      path: '/recommend'
      fullPath: '/recommend'
      preLoaderRoute: typeof RecommendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/': {
      id: '/destinations/'
      path: '/destinations'
      fullPath: '/destinations/'
      preLoaderRoute: typeof DestinationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/$id': {
      id: '/destinations/$id'
      path: '/destinations/$id'
      fullPath: '/destinations/$id'
      preLoaderRoute: typeof DestinationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  HistoryRoute: HistoryRoute,
  RecommendRoute: RecommendRoute,
  RegisterBusinessRoute: RegisterBusinessRoute,
  DestinationsIdRoute: DestinationsIdRoute,
  DestinationsIndexRoute: DestinationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
